Models/Wedding.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace LoginReg.Models
{
    public class Wedding
    {
        [Key]
        public int WeddingId { get; set; }
        [Required]
        [MinLength(3, ErrorMessage="Name must be 3 characters or longer!")]
        public string WedderOne { get; set; }
        [Required]
        [MinLength(3, ErrorMessage="Name must be 3 characters or longer!")]
        public string WedderTwo { get; set; }
        [DateInTheFuture]
        public DateTime Date { get; set; }
        [Required]
        [MinLength(3, ErrorMessage="Address must be 3 characters or longer!")]
        public string WeddingAddress{get; set; }
        public DateTime CreatedAt {get; set; } = DateTime.Now;
        public DateTime UpdatedAt {get; set; } = DateTime.Now;
        public int UserId { get; set; }

        public List<Association> Guests { get; set; }

    }
}

Controllers/WeddingController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using LoginReg.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Identity;

namespace LoginReg.Controllers
{
    public class WeddingController : Controller
    {
        private LoginRegContext dbContext;

        public WeddingController(LoginRegContext context)
        {
            dbContext = context;
        }

        [Route("success")]
        [HttpGet]
        public IActionResult Success()
        {
            int? userId = HttpContext.Session.GetInt32("UserId");
            if (userId == null)
                return RedirectToAction("Index", "Home");
            List<Wedding> AllWeddings = dbContext.Weddings
                .Include(w => w.Guests)
                .ThenInclude(a => a.User)
                .ToList();
            ViewBag.UserId = userId;
            Console.WriteLine(userId);


            return View("Success", AllWeddings);
        }

        [Route("/add/wedding")]
        [HttpGet]
        public IActionResult AddWedding()
        {
            int? userId = HttpContext.Session.GetInt32("UserId");
            if (userId == null)
                return RedirectToAction("Index", "Home");
            return View("AddWedding");
        }


        [Route("/create/wedding")]
        [HttpPost]
        public IActionResult CreateWedding(Wedding newWedding)
        {
            if (ModelState.IsValid)
            {
                int? userId = HttpContext.Session.GetInt32("UserId");
                newWedding.UserId = (int)userId;
                dbContext.Add(newWedding);
                dbContext.SaveChanges();
                return RedirectToAction("ViewWedding", new { weddingId = newWedding.WeddingId });
            }
            else
                return View("AddWedding");
        }

        [Route("/add/{userId}/{weddingId}")]
        [HttpGet]
        public IActionResult AddUserToWedding(int userId, int weddingId)
        {
            Wedding oneWedding = dbContext.Weddings.FirstOrDefault(w => w.WeddingId == weddingId);
            User oneUser = dbContext.Users.FirstOrDefault(u => u.UserId == userId);
            Association newAssociation = new Association()
            {
                WeddingId = oneWedding.WeddingId,
                UserId = oneUser.UserId
            };
            dbContext.Associations.Add(newAssociation);
            dbContext.SaveChanges();
            return RedirectToAction("Success");
        }
        [Route("/remove/{userId}/{weddingId}")]
        [HttpGet]
        public IActionResult RemoveUserFromWedding(int userId, int weddingId)
        {
            Wedding oneWedding = dbContext.Weddings.FirstOrDefault(w => w.WeddingId == weddingId);
            User oneUser = dbContext.Users.FirstOrDefault(u => u.UserId == userId);
            Association oneAssociation = dbContext.Associations.FirstOrDefault(a => a.UserId == userId && a.WeddingId == weddingId);

            oneWedding.Guests.Remove(oneAssociation);
            dbContext.SaveChanges();
            return RedirectToAction("Success");
        }

        [Route("/view/{weddingId}")]
        [HttpGet]
        public IActionResult ViewWedding(int weddingId)
        {
            int? userId = HttpContext.Session.GetInt32("UserId");
            if (userId == null)
                return RedirectToAction("Index", "Home");
            List<Association> users = dbContext.Associations
            .Include(u => u.User)
             .Where(u => u.WeddingId == weddingId)
             .ToList();


            Wedding oneWedding = dbContext.Weddings.FirstOrDefault(w => w.WeddingId == weddingId);
            return View(oneWedding);
        }
        [Route("/delete/{weddingId}")]
        [HttpGet]
        public IActionResult DeleteWedding(int weddingId)
        {
            Wedding oneWedding = dbContext.Weddings.FirstOrDefault(w => w.WeddingId == weddingId);
            dbContext.Remove(oneWedding);
            dbContext.SaveChanges();
            return RedirectToAction("Success");
        }
    }
}

Views/Wedding/AddWedding.cshtml
@model Wedding
<h1>Add Wedding</h1>
<body>
<form asp-action="CreateWedding" asp-controller="Wedding" method="post">
        <span asp-validation-for="WedderOne"></span><br>
        <label asp-for="WedderOne"></label><br>
        <input asp-for="WedderOne"><br>
        <span asp-validation-for="WedderTwo"></span><br>
        <label asp-for="WedderTwo"></label><br>
        <input asp-for="WedderTwo"><br>
        <span asp-validation-for="WeddingAddress"></span><br>
        <label asp-for="WeddingAddress"></label><br>
        <input asp-for="WeddingAddress"><br>
        <span asp-validation-for="Date"></span><br>
        <label asp-for="Date"></label><br>
        <input type ="date" asp-for="Date"><br>
<button>Add Wedding</button>
</form>

</body>

Views/Wedding/Success.cshtml
@using System.Collections.Generic
@using LoginReg.Models
@model List<Wedding>

<a href ="/logout">Logout</a>
<a href ="/add/wedding">Add Wedding</a>
    <table style="width:50%">
    <tr>
    <th>Wedding</th>
    <th>Date</th> 
    <th>Guests</th>
    <th>Action</th>
    </tr>

    @foreach(var w in @Model)
    {
  <tr>
    <td><a href = "/view/@w.WeddingId">@w.WedderOne & @w.WedderTwo</a></td>
    <td>@w.Date</td>
    <td>@w.Guests.Count</td>
    @if(@w.UserId == @ViewBag.UserId)
    {
        <td><a href ="/delete/@w.WeddingId">Delete</a></td>
    } 
    else if(@w.Guests.Any(g => g.UserId == @ViewBag.UserId))
    {
    <td><a href ="/remove/@ViewBag.UserId/@w.WeddingId">Un-RSPV</a></td>
    }else if(@w.Guests.Count ==0)
    {
        <td><a href ="/add/@ViewBag.UserId/@w.WeddingId">RSPV</a></td>
    }
    else
    {
    <td><a href ="/add/@ViewBag.UserId/@w.WeddingId">RSPV</a></td>
    }
  </tr>

    }
  

  </table>

Views/Wedding/ViewWedding.cshtml
@using System.Collections.Generic
@using LoginReg.Models
@model Wedding

<a href ="/logout">Logout</a>
<a href ="/success">All Weddings</a>
<h1>@Model.WedderOne and @Model.WedderTwo Wedding</h1>
<h2>Date: @Model.Date</h2>
@if (@Model.Guests != null)
{
@foreach (var u in @Model.Guests)
{
    <p>@u.User.FirstName @u.User.LastName</p>
}
}